version: '3.4'

services:
  urlshortener:
    image: urlshortener
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/flaskblog
    depends_on:
      - mongodb
    environment:
      - REDIRECT_ADMIN_PASSWORD=phase-services
      - MONGO_INITDB_DATABSE=phase-services
      - MONGO_INITDB_ROOT_USERNAME=phase-services
      - MONGO_INITDB_ROOT_PASSWORD=phase-services

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABSE=phase-services
      - MONGO_INITDB_ROOT_USERNAME=phase-services
      - MONGO_INITDB_ROOT_PASSWORD=phase-services
     
   
    ports: 
     - 27017:27017
    