version: '3.4'

services:
  urlshortener:
    image: urlshortener
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    
    ports:
      - 27017:27017
